# Generated by Django 5.1.4 on 2024-12-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField()),
                ('caption', models.CharField(max_length=250)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.ImageField(max_length=255, upload_to='temp_images')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('collection_id', models.IntegerField()),
                ('file_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('remove_bg', models.BooleanField(default=False)),
                ('remove_wm', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'temp_images_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temp_products_table',
                'managed': False,
            },
        ),
    ]
